// AUTH
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

// PROJECT
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const EDIT_PROJECT_REQUEST = 'EDIT_PROJECT_REQUEST';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_FAILURE = 'EDIT_PROJECT_FAILURE';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

// JOIN PROJECT
export const JOIN_PROJECT_REQUEST = 'JOIN_PROJECT_REQUEST';
export const JOIN_PROJECT_SUCCESS = 'JOIN_PROJECT_SUCCESS';
export const JOIN_PROJECT_FAILURE = 'JOIN_PROJECT_FAILURE';

// REMOVE USER FROM PROJECT
export const REMOVE_USER_FROM_PROJECT_REQUEST = 'REMOVE_USER_FROM_PROJECT_REQUESTT';
export const REMOVE_USER_FROM_PROJECT_SUCCESS = 'REMOVE_USER_FROM_PROJECT_SUCCESS';
export const REMOVE_USER_FROM_PROJECT_FAILURE = 'REMOVE_USER_FROM_PROJECT_FAILURE';

// GET USER PROJECTS
export const GET_USER_PROJECTS_REQUEST = 'GET_USER_PROJECTS_REQUEST';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILURE = 'GET_USER_PROJECTS_FAILURE';

// GET PROJECT DETAILS
export const GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST';
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS';
export const GET_PROJECT_DETAILS_FAILURE = 'GET_PROJECT_DETAILS_FAILURE';


// TODO
export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE';

export const GET_USER_TODOS_REQUEST = 'GET_USER_TODOS_REQUEST';
export const GET_USER_TODOS_SUCCESS = 'GET_USER_TODOS_SUCCESS';
export const GET_USER_TODOS_FAILURE = 'GET_USER_TODOS_FAILURE';

export const GET_TODO_BY_ID_REQUEST = 'GET_TODO_BY_ID_REQUEST';
export const GET_TODO_BY_ID_SUCCESS = 'GET_TODO_BY_ID_SUCCESS';
export const GET_TODO_BY_ID_FAILURE = 'GET_TODO_BY_ID_FAILURE';

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const ASSIGN_TODO_REQUEST = 'ASSIGN_TODO_REQUEST';
export const ASSIGN_TODO_SUCCESS = 'ASSIGN_TODO_SUCCESS';
export const ASSIGN_TODO_FAILURE = 'ASSIGN_TODO_FAILURE';

export const UPDATE_TODO_REVIEW_REQUEST = 'UPDATE_TODO_REVIEW_REQUEST';
export const UPDATE_TODO_REVIEW_SUCCESS = 'UPDATE_TODO_REVIEW_SUCCESS';
export const UPDATE_TODO_REVIEW_FAILURE = 'UPDATE_TODO_REVIEW_FAILURE';


// CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';